### ISSUE TITLE
how to use mutiGPU train?

### ISSUE THREAD

**Issue by ghost** [Andras7/gpt2-pytorch#1]
hi
@Andras7 
thanks for your work, it really help me
but i wonder how to use mutiGPU for training?

**Comment by Andras7** [comment]
Hi,

It will be ease, you should follow this tutorial: https://pytorch.org/tutorials/beginner/former_torchies/parallelism_tutorial.html

**Comment by ghost** [comment]
Thanks
Maybe my GPUs are too weak
Train code stuck and motionless
